robot_positions:
  home: [0.35, 1.079, 0.862, 3.14, 0, 1.57] # Location of tool0

camera:
  camera_frame: "camera_depth_optical_frame"
  calibration_plate_aruco: [0.8, 0.0, 0.9, -3.14, 0, 1.57]
  calibration_plate_id: 2
  filters:
    localizer_bbox: [-1,-1,-2.0,1,1,0.3] # x,y,z limits with respect to camera frame
  aruco_frames: # fiducials 1-5 with respect to tool0
    - [] # Part aruco
    - [] # Boundary arucos
    - []
    - []
    - []

stl_params:
  name: "composite_mold"
  directory_path: "/database/meshes"
  transform: [ 0.3, 0.8, 0.5, 0.0, 0.0, 1.57 ] # xyzrpy. Only for simulated camera.
  color: [0.5, 0.5, 0.5]

# Collision box
# position is x, y, z
# orientation q: x, y, z, w
collision_boxes:
  front_floor:
    name: "front_floor"
    frame_id: "base_link"
    position: [1.8, 0.0, 0.6]
    orientation: [0.0, 0.0, 0.0, 1.0]
    dimension: [2.0, 2.0, 0.01]

  left_floor:
    name: "left_floor"
    frame_id: "base_link"
    position: [0.0, 1.6, 0.4]
    orientation: [0.0, 0.0, 0.0, 1.0]
    dimension: [2.0, 2.0, 0.01]

  right_floor:
    name: "right_floor"
    frame_id: "base_link"
    position: [0.0, -2.0, 0.5]
    orientation: [0.0, 0.0, 0.0, 1.0]
    dimension: [2.0, 2.0, 0.01]

  left_wall:
    name: "left_wall"
    frame_id: "base_link"
    position: [0.0, 1.5, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
    dimension: [5.0, 0.01, 5.0]
  
  right_wall:
    name: "right_wall"
    frame_id: "base_link"
    position: [0.0, -1.0, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
    dimension: [5.0, 0.01, 5.0]

  ceiling:
    name: "ceiling"
    frame_id: "base_link"
    position: [0.0, 0.0, 1.7]
    orientation: [0.0, 0.0, 0.0, 1.0]
    dimension: [5.0, 5.0, 0.01]
  
  back_wall:
    name: "back_wall"
    frame_id: "base_link"
    position: [-0.5, 0.0, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
    dimension: [0.01, 5.0, 5.0]

  front_wall:
    name: "front_wall"
    frame_id: "base_link"
    position: [1.7, 0.0, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
    dimension: [0.01, 5.0, 5.0]